version: '3.8'

services:
  app:
    build:
      context: .
      args:
        www_data_uid: 1000
        www_data_gid: 1000
    container_name: i-billboard-app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html

  redis:
    image: redis:latest
    container_name: i-billboard-redis
    ports:
      - "6379:6379"
